apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride | default (include "bankapp.fullname" .) }}
  namespace: {{ .Values.namespace }}
  labels:
  {{ include "bankapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ include "bankapp.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
