replicaCount: 1

image:
  repository: bitnami/kafka
  tag: 3.7
  pullPolicy: IfNotPresent

zookeeper:
  replicaCount: 1
  image:
    repository: bitnami/zookeeper
    tag: 3.9
  storage: 2Gi

kafka:
  storage: 5Gi
  servicePort: 9092
  externalAccess: false

resources: {}
