apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstash.fullname" . }}
  namespace: bankapp
  labels:
    app: {{ include "logstash.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: beats
  selector:
    app: {{ include "logstash.name" . }}
