apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: bankapp
  labels:
    app: grafana
data:
  prometheus-datasource.yaml: |
{{ .Files.Get "provisioning/datasources/prometheus.yaml" | indent 4 }}

  dashboards-provider.yaml: |
{{ .Files.Get "provisioning/dashboards/dashboards.yaml" | indent 4 }}

  microservices.json: |
{{ .Files.Get "dashboards/microservices.json" | indent 4 }}
