apiVersion: v1
kind: Service
metadata:
  name: exchange-generator
  namespace: bankapp
spec:
  selector:
    app: exchange-generator
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP
