apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer
  namespace: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer
  template:
    metadata:
      labels:
        app: transfer
    spec:
      containers:
        - name: transfer
          image: bankapp-transfer:local
          env:
            - name: CONFIG_SERVER_URI
              value: "http://config-server:8888"
            - name: EUREKA_URI
              value: "http://eureka:8761/eureka/"
            - name: KEYCLOAK_TOKEN_URI
              value: "http://keycloak:8089/realms/master/protocol/openid-connect/token"
            - name: KEYCLOAK_ISSUER_URI
              value: "http://keycloak:8089/realms/master"