apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocker
  namespace: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blocker
  template:
    metadata:
      labels:
        app: blocker
    spec:
      containers:
        - name: blocker
          image: bankapp-blocker:local
          env:
            - name: CONFIG_SERVER_URI
              value: "http://config-server:8888"
            - name: EUREKA_URI
              value: "http://eureka:8761/eureka/"
            - name: KEYCLOAK_ISSUER_URI
              value: "http://keycloak:8089/realms/master"
          ports:
            - containerPort: 8087