image:
  repository: bankapp-exchange-generator
  tag: local

fullnameOverride: "exchange-generator"

service:
  port: 8084

env:
  CONFIG_SERVER_URI: "http://config-server:8888"
  EUREKA_URI: "http://eureka:8761/eureka/"
  KEYCLOAK_TOKEN_URI: "http://keycloak:8089/realms/master/protocol/openid-connect/token"
