image:
  repository: quay.io/keycloak/keycloak
  tag: 26.1.3

fullnameOverride: "keycloak"

service:
  port: 8089

args:
  - "start-dev"
  - "--import-realm"
  - "--http-port=8089"

env:
  KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
  TZ: "Europe/Samara"

volumeMounts:
  - name: realm-volume
    mountPath: /opt/keycloak/data/import/realm-export.json
    subPath: realm-export.json

volumes:
  - name: realm-volume
    configMap:
      name: keycloak-realm
      items:
        - key: realm-export.json
          path: realm-export.json
