image:
  repository: bankapp-transfer
  tag: local

fullnameOverride: "transfer"

service:
  port: 8086

env:
  CONFIG_SERVER_URI: "http://config-server:8888"
  EUREKA_URI: "http://eureka:8761/eureka/"
  KEYCLOAK_TOKEN_URI: "http://keycloak:8089/realms/master/protocol/openid-connect/token"
  KEYCLOAK_ISSUER_URI: "http://keycloak:8089/realms/master"
