image:
  repository: bankapp-cash
  tag: local

fullnameOverride: "cash"

service:
  port: 8081

env:
  CONFIG_SERVER_URI: "http://config-server:8888"
  EUREKA_URI: "http://eureka:8761/eureka/"
  KEYCLOAK_TOKEN_URI: "http://keycloak:8080/realms/master/protocol/openid-connect/token"
