global:
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'cash:8081'
          - 'account:8082'
          - 'notification:8082'
          - 'exchange-generator:8084'
          - 'exchange:8085'
          - 'transfer:8086'
          - 'blocker:8087'
          - 'front:8088'
