apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: bankapp
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9200
      name: http
    - port: {{ .Values.service.transportPort }}
      targetPort: 9300
      name: transport
  selector:
    app: {{ .Release.Name }}
